# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import win32api
import win32con
from PyQt5 import QtCore, QtWidgets
from PyQt5.Qt import *
from PyQt5.QtGui import QPixmap, QPalette

import main as m
from until import get_resource_path


class Ui_MainWindow(object):

    def __init__(self):
        super(Ui_MainWindow, self).__init__()
        self.mywork = WorkThread()
        self.mywork.x = 25
        self.mywork.y = 99
        self.mywork.z = 100
        self.mywork.a = 13
        self.mywork.b = 30

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(668, 747)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.qifeihuaixiang = QtWidgets.QLineEdit(self.centralwidget)
        self.qifeihuaixiang.setObjectName("qifeihuaixiang")
        self.gridLayout.addWidget(self.qifeihuaixiang, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.qifeigaodu = QtWidgets.QLineEdit(self.centralwidget)
        self.qifeigaodu.setObjectName("qifeigaodu")
        self.gridLayout.addWidget(self.qifeigaodu, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.zhifeijuli = QtWidgets.QLineEdit(self.centralwidget)
        self.zhifeijuli.setObjectName("zhifeijuli")
        self.gridLayout.addWidget(self.zhifeijuli, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 1)
        self.panxuanchangdu = QtWidgets.QLineEdit(self.centralwidget)
        self.panxuanchangdu.setObjectName("panxuanchangdu")
        self.gridLayout.addWidget(self.panxuanchangdu, 7, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 8, 0, 1, 1)
        self.xiangxiaxiuzheng = QtWidgets.QLineEdit(self.centralwidget)
        self.xiangxiaxiuzheng.setObjectName("xiangxiaxiuzheng")
        self.gridLayout.addWidget(self.xiangxiaxiuzheng, 9, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.yingyong = QtWidgets.QPushButton(self.centralwidget)
        self.yingyong.setObjectName("yingyong")
        self.horizontalLayout.addWidget(self.yingyong)
        self.huifumoren = QtWidgets.QPushButton(self.centralwidget)
        self.huifumoren.setObjectName("huifumoren")
        self.horizontalLayout.addWidget(self.huifumoren)
        self.kaishi = QtWidgets.QPushButton(self.centralwidget)
        self.kaishi.setObjectName("kaishi")
        self.horizontalLayout.addWidget(self.kaishi)
        self.jieshu = QtWidgets.QPushButton(self.centralwidget)
        self.jieshu.setObjectName("jieshu")
        self.horizontalLayout.addWidget(self.jieshu)
        self.gridLayout.addLayout(self.horizontalLayout, 10, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 668, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.yingyong.clicked.connect(self.change)  # type: ignore
        self.huifumoren.clicked.connect(self.changeTodefault)  # type: ignore
        self.kaishi.clicked.connect(self.mythredStart)  # type: ignore
        self.jieshu.clicked.connect(self.mythredStoop)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        palette = QPalette()
        bg_img = QPixmap(get_resource_path("pic/beijingtupian.png"))  # 背景图片路径
        palette.setBrush(QPalette.Background, QBrush(bg_img))
        MainWindow.setPalette(palette)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "thunder"))
        self.label.setText(_translate("MainWindow", "功能正在开发中，敬请期待"))
        self.label_2.setText(_translate("MainWindow", "功能正在开发中，敬请期待"))
        self.label_3.setText(_translate("MainWindow", "功能正在开发中，敬请期待"))
        self.label_4.setText(_translate("MainWindow", "功能正在开发中，敬请期待"))
        self.label_5.setText(_translate("MainWindow", "功能正在开发中，敬请期待"))
        self.yingyong.setText(_translate("MainWindow", "功能正在开发中，敬请期待"))
        self.huifumoren.setText(_translate("MainWindow", "功能正在开发中，敬请期待"))
        self.kaishi.setText(_translate("MainWindow", "开始"))
        self.jieshu.setText(_translate("MainWindow", "结束"))

    def mythredStart(self):
        self.mywork.start()

    def mythredStoop(self):
        self.mywork.terminate()

    def change(self):
        if self.mywork.isRunning():
            win32api.MessageBox(0, "请先停止脚本", "消息提示", win32con.MB_OK)
        elif self.qifeihuaixiang.text() == "" or self.zhifeijuli.text() == "" or self.xiangxiaxiuzheng.text() == "" or self.qifeigaodu.text() == "" or self.panxuanchangdu.text() == "":
            win32api.MessageBox(0, "请输入数值", "消息提示", win32con.MB_OK)
        else:
            self.mywork.x = self.qifeihuaixiang.text()
            self.mywork.y = self.zhifeijuli.text()
            self.mywork.z = self.xiangxiaxiuzheng.text()
            self.mywork.a = self.qifeigaodu.text()
            self.mywork.b = self.panxuanchangdu.text()
            print(self.mywork.x)
            print(self.mywork.y)
            print(self.mywork.z)
            print(self.mywork.a)
            print(self.mywork.b)

    def changeTodefault(self):
        if self.mywork.isRunning():
            win32api.MessageBox(0, "请先停止脚本", "消息提示", win32con.MB_OK)
        else:
            win32api.MessageBox(0, "恢复成功", "消息提示", win32con.MB_OK)
            self.mywork.x = 25
            self.mywork.y = 99
            self.mywork.z = 200
            self.mywork.a = 13
            self.mywork.b = 30
            print(self.mywork.x)
            print(self.mywork.y)
            print(self.mywork.z)


class WorkThread(QThread):
    # 自定义信号对象。参数str就代表这个信号可以传一个字符串
    # postSignal = pyqtSignal(int, int, int)
    x = 0
    y = 0
    z = 0
    a = 0
    b = 0

    def __int__(self):
        # 初始化函数
        super(WorkThread, self).__init__()
        self.x = 25
        self.y = 99
        self.z = 100
        self.a = 13
        self.b = 30

    def run(self):
        m.main()
